extends:
  - eslint:recommended
  - airbnb-base
  - prettier
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - lib/
rules:
  import/no-unresolved: off
  import/extensions: off
  "@typescript-eslint/explicit-function-return-type": error
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
